# ============================
# 變數清單
# ============================

# 所有 cols
cols = [
    'Fund_id', '投信名稱', 'Year_month_lag1', 'Firm_id', '標的名稱', 'TSE',
    'Year', 'hold_lag1', 'equity_hold_lag1', 'debt_hold_lag1',
    'engagement_t', 'engage_without_hold', 'Conglo', 'Seg', 'Comp',
    'Foreign_Dummy', 'Foreign_Sales_Ratio', 'TESG_score_t',
    'TESG_score_lead1', 'TESG_score_lead2', 'TESG_score_lead3',
    'TESG_grade_t', 'TESG_grade_lead1', 'TESG_grade_lead2',
    'TESG_grade_lead3', 'E_score_t', 'E_score_lead1', 'E_score_lead2',
    'E_score_lead3', 'S_score_t', 'S_score_lead1', 'S_score_lead2',
    'S_score_lead3', 'G_score_t', 'G_score_lead1', 'G_score_lead2',
    'G_score_lead3', 'GHG_score_t', 'GHG_score_lead1', 'GHG_score_lead2',
    'GHG_score_lead3', 'Energy_score_t', 'Energy_score_lead1',
    'Energy_score_lead2', 'Energy_score_lead3', 'Water_score_t',
    'Water_score_lead1', 'Water_score_lead2', 'Water_score_lead3',
    'Waste_score_t', 'Waste_score_lead1', 'Waste_score_lead2',
    'Waste_score_lead3', 'Human_rights_score_t',
    'Human_rights_score_lead1', 'Human_rights_score_lead2',
    'Human_rights_score_lead3', 'Data_security_score_t',
    'Data_security_score_lead1', 'Data_security_score_lead2',
    'Data_security_score_lead3', 'Product_quality_score_t',
    'Product_quality_score_lead1', 'Product_quality_score_lead2',
    'Product_quality_score_lead3', 'Employee_metrics_score_t',
    'Employee_metrics_score_lead1', 'Employee_metrics_score_lead2',
    'Employee_metrics_score_lead3', 'Employee_health_score_t',
    'Employee_health_score_lead1', 'Employee_health_score_lead2',
    'Employee_health_score_lead3', 'Ownership_control_score_t',
    'Ownership_control_score_lead1', 'Ownership_control_score_lead2',
    'Ownership_control_score_lead3', 'Stakeholder_fairness_score_t',
    'Stakeholder_fairness_score_lead1', 'Stakeholder_fairness_score_lead2',
    'Stakeholder_fairness_score_lead3', 'Governance_transparency_score_t',
    'Governance_transparency_score_lead1',
    'Governance_transparency_score_lead2',
    'Governance_transparency_score_lead3', 'TESG_rank_t',
    'TESG_rank_lead1', 'TESG_SASB_main_rank_t',
    'TESG_SASB_main_rank_lead1', 'TESG_SASB_sec_rank_t',
    'TESG_SASB_sec_rank_lead1', 'E_SASB_main_rank_t',
    'E_SASB_main_rank_lead1', 'E_SASB_sec_rank_t',
    'E_SASB_sec_rank_lead1', 'S_SASB_main_rank_t',
    'S_SASB_main_rank_lead1', 'S_SASB_sec_rank_t',
    'S_SASB_sec_rank_lead1', 'G_SASB_main_rank_t',
    'G_SASB_main_rank_lead1', 'G_SASB_sec_rank_t',
    'G_SASB_sec_rank_lead1', 'GHG_SASB_main_rank_t',
    'GHG_SASB_main_rank_lead1', 'GHG_SASB_sec_rank_t',
    'GHG_SASB_sec_rank_lead1', 'Energy_SASB_main_rank_t',
    'Energy_SASB_main_rank_lead1', 'Energy_SASB_sec_rank_t',
    'Energy_SASB_sec_rank_lead1', 'Water_SASB_main_rank_t',
    'Water_SASB_main_rank_lead1', 'Water_SASB_sec_rank_t',
    'Water_SASB_sec_rank_lead1', 'Waste_SASB_main_rank_t',
    'Waste_SASB_main_rank_lead1', 'Waste_SASB_sec_rank_t',
    'Waste_SASB_sec_rank_lead1', 'Human_rights_SASB_main_rank_t',
    'Human_rights_SASB_main_rank_lead1',
    'Human_rights_SASB_sec_rank_t',
    'Human_rights_SASB_sec_rank_lead1',
    'Data_security_SASB_main_rank_t',
    'Data_security_SASB_main_rank_lead1',
    'Data_security_SASB_sec_rank_t',
    'Data_security_SASB_sec_rank_lead1',
    'Product_quality_SASB_main_rank_t',
    'Product_quality_SASB_main_rank_lead1',
    'Product_quality_SASB_sec_rank_t',
    'Product_quality_SASB_sec_rank_lead1',
    'Employee_metrics_SASB_main_rank_t',
    'Employee_metrics_SASB_main_rank_lead1',
    'Employee_metrics_SASB_sec_rank_t',
    'Employee_metrics_SASB_sec_rank_lead1',
    'Employee_health_SASB_main_rank_t',
    'Employee_health_SASB_main_rank_lead1',
    'Employee_health_SASB_sec_rank_t',
    'Employee_health_SASB_sec_rank_lead1',
    'Ownership_control_SASB_main_rank_t',
    'Ownership_control_SASB_main_rank_lead1',
    'Ownership_control_SASB_sec_rank_t',
    'Ownership_control_SASB_sec_rank_lead1',
    'Stakeholder_fairness_SASB_main_rank_t',
    'Stakeholder_fairness_SASB_main_rank_lead1',
    'Stakeholder_fairness_SASB_sec_rank_t',
    'Stakeholder_fairness_SASB_sec_rank_lead1',
    'Governance_transparency_SASB_main_rank_t',
    'Governance_transparency_SASB_main_rank_lead1',
    'Governance_transparency_SASB_sec_rank_t',
    'Governance_transparency_SASB_sec_rank_lead1',
    'Size', 'l_Size', 'Lev', 'Cash_r', 'ROA', 'Current_Ratio',
    'Tangibility_r', 'Board_Independ_r', 'Age', 'l_Age', 'SalesGrowth'
]

# winsorize cols
win_cols = [
    "Comp",
    "Foreign_Sales_Ratio",
    "TESG_score_t",
    "TESG_score_lead1",
    "TESG_score_lead2",
    "TESG_score_lead3",
    "E_score_t",
    "E_score_lead1",
    "E_score_lead2",
    "E_score_lead3",
    "S_score_t",
    "S_score_lead1",
    "S_score_lead2",
    "S_score_lead3",
    "G_score_t",
    "G_score_lead1",
    "G_score_lead2",
    "G_score_lead3",
    "GHG_score_t",
    "GHG_score_lead1",
    "GHG_score_lead2",
    "GHG_score_lead3",
    "Energy_score_t",
    "Energy_score_lead1",
    "Energy_score_lead2",
    "Energy_score_lead3",
    "Water_score_t",
    "Water_score_lead1",
    "Water_score_lead2",
    "Water_score_lead3",
    "Waste_score_t",
    "Waste_score_lead1",
    "Waste_score_lead2",
    "Waste_score_lead3",
    "Human_rights_score_t",
    "Human_rights_score_lead1",
    "Human_rights_score_lead2",
    "Human_rights_score_lead3",
    "Data_security_score_t",
    "Data_security_score_lead1",
    "Data_security_score_lead2",
    "Data_security_score_lead3",
    "Product_quality_score_t",
    "Product_quality_score_lead1",
    "Product_quality_score_lead2",
    "Product_quality_score_lead3",
    "Employee_metrics_score_t",
    "Employee_metrics_score_lead1",
    "Employee_metrics_score_lead2",
    "Employee_metrics_score_lead3",
    "Employee_health_score_t",
    "Employee_health_score_lead1",
    "Employee_health_score_lead2",
    "Employee_health_score_lead3",
    "Ownership_control_score_t",
    "Ownership_control_score_lead1",
    "Ownership_control_score_lead2",
    "Ownership_control_score_lead3",
    "Stakeholder_fairness_score_t",
    "Stakeholder_fairness_score_lead1",
    "Stakeholder_fairness_score_lead2",
    "Stakeholder_fairness_score_lead3",
    "Governance_transparency_score_t",
    "Governance_transparency_score_lead1",
    "Governance_transparency_score_lead2",
    "Governance_transparency_score_lead3",
    "l_Size",
    "Lev",
    "Cash_r",
    "ROA",
    "Current_Ratio",
    "Tangibility_r",
    "Board_Independ_r",
    "l_Age",
    "SalesGrowth",
]

# 應變數
dep_var = ['這裡放你的Y']

# 主要解釋變數
main_vars = ['Conglo', 'Seg', 'Comp', 'Foreign_Dummy', 'Foreign_Sales_Ratio']

# 控制變數
control_vars = [
    'l_Size', 'Lev', 'Cash_r', 'ROA', 'Current_Ratio',
    'Tangibility_r', 'Board_Independ_r', 'l_Age', 'SalesGrowth',
]

# 固定效果
fe_vars = ['Firm_id', 'Year']

# 共變數矩陣
corr_vars = [
    'Conglo', 'Seg', 'Comp', 'Foreign_Dummy', 'Foreign_Sales_Ratio', 
    'TESG_score_t', 'TESG_score_lead1', 'TESG_score_lead2', 'TESG_score_lead3', 
    'TESG_grade_t', 'TESG_grade_lead1', 'TESG_grade_lead2', 'TESG_grade_lead3', 
    'E_score_t', 'E_score_lead1', 'E_score_lead2', 'E_score_lead3', 
    'S_score_t', 'S_score_lead1', 'S_score_lead2', 'S_score_lead3', 
    'G_score_t', 'G_score_lead1', 'G_score_lead2', 'G_score_lead3', 
    'GHG_score_t', 'GHG_score_lead1', 'GHG_score_lead2', 'GHG_score_lead3', 
    'Energy_score_t', 'Energy_score_lead1', 'Energy_score_lead2', 'Energy_score_lead3', 
    'Water_score_t', 'Water_score_lead1', 'Water_score_lead2', 'Water_score_lead3', 
    'Waste_score_t', 'Waste_score_lead1', 'Waste_score_lead2', 'Waste_score_lead3', 
    'Human_rights_score_t', 'Human_rights_score_lead1', 'Human_rights_score_lead2', 'Human_rights_score_lead3', 
    'Data_security_score_t', 'Data_security_score_lead1', 'Data_security_score_lead2', 'Data_security_score_lead3', 
    'Product_quality_score_t', 'Product_quality_score_lead1', 'Product_quality_score_lead2', 'Product_quality_score_lead3', 
    'Employee_metrics_score_t', 'Employee_metrics_score_lead1', 'Employee_metrics_score_lead2', 'Employee_metrics_score_lead3', 
    'Employee_health_score_t', 'Employee_health_score_lead1', 'Employee_health_score_lead2', 'Employee_health_score_lead3', 
    'Ownership_control_score_t', 'Ownership_control_score_lead1', 'Ownership_control_score_lead2', 'Ownership_control_score_lead3', 
    'Stakeholder_fairness_score_t', 'Stakeholder_fairness_score_lead1', 'Stakeholder_fairness_score_lead2', 'Stakeholder_fairness_score_lead3', 
    'Governance_transparency_score_t', 'Governance_transparency_score_lead1', 'Governance_transparency_score_lead2', 'Governance_transparency_score_lead3', 
    'l_Size', 'Lev', 'Cash_r', 'ROA', 'Current_Ratio', 'Tangibility_r', 'Board_Independ_r', 'Age', 'l_Age', 'SalesGrowth'
]
