# -*- coding: utf-8 -*-
"""歡迎使用 Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import pandas as pd

# 1. 讀取原始檔案 (請確保檔名與上傳的一致)
# 這裡假設檔案格式為 CSV，如果是 Excel 請改用 pd.read_excel
df_idx = pd.read_csv('2020_S0.csv')
df_txo = pd.read_csv('Option_2020')

# 2. 統一日期格式為 pandas 的 datetime 物件以利計算
df_idx['Date_dt'] = pd.to_datetime(df_idx['年月日'])
df_txo['Expiry_dt'] = pd.to_datetime(df_txo['最後結算日'])

# 3. 將結算日排序，確保計算邏輯正確
df_txo = df_txo.sort_values('Expiry_dt')

# 4. 建立合併邏輯
final_data = []

for _, row in df_idx.iterrows():
    curr_date = row['Date_dt']

    # 找到結算日大於或等於當前交易日的第一筆資料 (即最近的到期合約)
    potential_expiries = df_txo[df_txo['Expiry_dt'] >= curr_date]

    if not potential_expiries.empty:
        next_expiry = potential_expiries.iloc[0]

        # 計算 Maturity (自然日天數)
        maturity = (next_expiry['Expiry_dt'] - curr_date).days

        # 判斷當天是否為結算日
        is_expiry_day = (next_expiry['Expiry_dt'] == curr_date)

        # 整理成最終欄位格式
        final_data.append({
            'Date': curr_date.strftime('%Y/%m/%d'), # 格式化為 YYYY/MM/DD
            'S0': row['收盤價(元)'],
            'Maturity': maturity,
            'Contract': next_expiry['月份'],
            'ContractExpiryDate': next_expiry['Expiry_dt'].strftime('%Y%m'), # 只保留年月
            'TXO_Price': next_expiry['（TXO）'] if is_expiry_day else "" # 只有結算日才顯示價格
        })

# 5. 轉回 DataFrame 並匯出
df_result = pd.DataFrame(final_data)
df_result.to_csv('2020_Combined_Data.csv', index=False, encoding='utf-8-sig')

print("合併完成！檔案已儲存為 2020_Combined_Data.csv")
print(df_result.head())

import pandas as pd

def merge_risk_free_rate():
    # 1. 設定檔案名稱
    input_filename = '2020_Combined_Data.csv'
    output_filename = 'Index_2020_with_RF.csv'

    try:
        # 2. 讀取原始 CSV 檔案
        print(f"正在讀取檔案：{input_filename} ...")
        df = pd.read_csv(input_filename)

        # 3. 設定無風險利率 (依據 2020/08/01 一年期定存固定利率 0.79%)
        rf_yearly = 0.0079
        rf_daily = rf_yearly / 365

        # 4. 新增欄位
        df['Rf_Yearly'] = rf_yearly
        df['Rf_Daily'] = rf_daily

        # (選用) 如果你需要直接計算超額報酬，可以把下面這兩行的註解 (#) 拿掉
        # 假設你的指數收盤價欄位名稱叫做 'Close'，請自行更改為實際欄位名稱
        # df['Daily_Return'] = df['Close'].pct_change()
        # df['Excess_Return'] = df['Daily_Return'] - df['Rf_Daily']

        # 5. 匯出成新的 CSV 檔案 (使用 utf-8-sig 確保 Excel 打開中文不會亂碼)
        df.to_csv(output_filename, index=False, encoding='utf-8-sig')
        print(f"✅ 處理完成！檔案已儲存為：{output_filename}")

    except FileNotFoundError:
        print(f"❌ 找不到檔案！請確認 '{input_filename}' 是否與這支程式放在同一個資料夾中。")
    except Exception as e:
        print(f"❌ 發生錯誤：{e}")

# 執行函式
if __name__ == "__main__":
    merge_risk_free_rate()