# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m2kdH7_7putcF5IYfMTLy7hINDMeYMvS
"""

import zipfile
import pandas as pd
import os
from google.colab import drive

# 1. 掛載雲端硬碟
if not os.path.exists('/content/drive'):
    drive.mount('/content/drive')

# --- 設定路徑 (請根據你雲端硬碟的實際位置修改檔名) ---
zip_path = '/content/drive/MyDrive/Option_2022.zip'
output_path = '/content/drive/MyDrive/TXO_2022_Filtered.csv'

# 2. 準備處理
txo_data_list = []
processed_count = 0

print(f"🚀 開始預處理 {zip_path}...")

with zipfile.ZipFile(zip_path, 'r') as z:
    # 獲取壓縮檔內所有檔案清單
    all_files = [f for f in z.namelist() if f.endswith('.csv')]
    total_files = len(all_files)

    print(f"📦 偵測到 {total_files} 個 CSV 檔案，正在篩選 TXO 資料...")

    for file_name in all_files:
        try:
            # 直接從 ZIP 中開啟檔案，不解壓到磁碟
            with z.open(file_name) as f:
                # 根據期交所格式，通常是 big5 或 cp950 編碼
                # 如果讀取失敗，請嘗試 encoding='utf-8' 或 'utf-16'
                df = pd.read_csv(f, encoding='cp950', low_memory=False)

                # --- 過濾 TXO ---
                # 假設欄位名稱是 '商品代碼' 或 'Contract ID'
                # 如果你的欄位名不同，請修改這裡 (例如 df['商品代號'])
                if '商品代碼' in df.columns:
                    filtered_df = df[df['商品代碼'].str.strip() == 'TXO']
                elif 'Contract ID' in df.columns:
                    filtered_df = df[df['Contract ID'].str.strip() == 'TXO']
                else:
                    # 如果找不到欄位名，嘗試用第一欄過濾
                    filtered_df = df[df.iloc[:, 0].astype(str).str.contains('TXO')]

                if not filtered_df.empty:
                    txo_data_list.append(filtered_df)

            processed_count += 1
            if processed_count % 10 == 0:
                print(f"⏳ 已處理 {processed_count}/{total_files} 個檔案...")

        except Exception as e:
            print(f"⚠️ 讀取 {file_name} 時出錯: {e}")

# 3. 合併並儲存
if txo_data_list:
    print("🔄 正在合併所有 TXO 資料...")
    final_df = pd.concat(txo_data_list, ignore_index=True)

    # 儲存回雲端硬碟
    final_df.to_csv(output_path, index=False, encoding='utf-8-sig')
    print(f"✅ 預處理完成！")
    print(f"📂 篩選後的檔案已儲存至：{output_path}")
    print(f"📊 總共抓取到 {len(final_df)} 筆 TXO 資料。")
else:
    print("❌ 找不到任何符合 TXO 的資料，請檢查欄位名稱設定。")

import zipfile
import pandas as pd
import os
from google.colab import drive

# 1. 掛載雲端硬碟
if not os.path.exists('/content/drive'):
    drive.mount('/content/drive')

# 2. 設定路徑
zip_path = '/content/drive/MyDrive/Option_2022.zip'
# 新建一個資料夾來裝這 200 多個每日獨立檔案
output_folder = '/content/drive/MyDrive/TXO_2022_Daily'

# 如果資料夾不存在，就建立它
if not os.path.exists(output_folder):
    os.makedirs(output_folder)
    print(f"📁 已建立輸出資料夾：{output_folder}")

print(f"🚀 開始讀取 {zip_path}，準備產出每日獨立檔案...")

# 3. 開始逐檔處理
saved_files_count = 0

with zipfile.ZipFile(zip_path, 'r') as z:
    all_items = z.namelist()

    # 排除資料夾與 MAC 隱藏檔
    target_files = [f for f in all_items if not f.endswith('/') and '__MACOSX' not in f]
    total_files = len(target_files)

    print(f"📦 偵測到 {total_files} 個原始檔案，開始過濾 TXO...")

    for file_name in target_files:
        # 取得純檔名 (避免壓縮檔內有子資料夾結構影響存檔)
        base_name = os.path.basename(file_name)
        if not base_name.endswith('.csv'):
            base_name += '.csv' # 確保輸出有副檔名

        output_file_path = os.path.join(output_folder, base_name)

        # 為了避免 RAM 爆掉，一樣採用分批讀取
        has_txo = False
        first_chunk = True

        try:
            with z.open(file_name) as f:
                try:
                    chunk_iter = pd.read_csv(f, encoding='cp950', low_memory=False, chunksize=500000)
                except UnicodeDecodeError:
                    f = z.open(file_name)
                    chunk_iter = pd.read_csv(f, encoding='utf-8-sig', low_memory=False, chunksize=500000)

                for chunk in chunk_iter:
                    chunk.columns = chunk.columns.str.strip()

                    # 尋找 TXO 資料
                    if '商品代碼' in chunk.columns:
                        filtered_chunk = chunk[chunk['商品代碼'].astype(str).str.strip() == 'TXO']
                    elif '契約' in chunk.columns:
                        filtered_chunk = chunk[chunk['契約'].astype(str).str.strip() == 'TXO']
                    else:
                        filtered_chunk = chunk[chunk.iloc[:, 0].astype(str).str.strip() == 'TXO']

                    # 如果這批資料有 TXO，就寫入獨立的每日檔案中
                    if not filtered_chunk.empty:
                        has_txo = True
                        filtered_chunk.to_csv(output_file_path, mode='a', header=first_chunk, index=False, encoding='utf-8-sig')
                        first_chunk = False

            if has_txo:
                saved_files_count += 1
                if saved_files_count % 10 == 0:
                    print(f"✅ 已成功產出 {saved_files_count} 個 TXO 獨立檔案...")
            else:
                print(f"⚠️ {base_name} 中沒有找到 TXO 資料，已略過。")

        except Exception as e:
            print(f"❌ 處理 {base_name} 時發生錯誤: {e}")

print(f"\n🎉 大功告成！總共成功產出了 {saved_files_count} 個每日 TXO 獨立 CSV 檔。")
print(f"📂 請前往你的 Google 雲端硬碟查看：{output_folder} 資料夾")

import zipfile
import pandas as pd
import os
import io
from google.colab import drive

# 1. 掛載雲端硬碟
if not os.path.exists('/content/drive'):
    drive.mount('/content/drive')

# 2. 設定路徑
zip_path = '/content/drive/MyDrive/Option_2022.zip'
output_folder = '/content/drive/MyDrive/TXO_2022_Daily'

if not os.path.exists(output_folder):
    os.makedirs(output_folder)
    print(f"📁 已建立輸出資料夾：{output_folder}")

# 3. 處理單一 CSV 檔案的核心函數
def process_csv_file(z_file, file_name, output_file_path):
    has_txo = False
    first_chunk = True

    def process_chunks(encoding):
        nonlocal has_txo, first_chunk

        # 如果是重新嘗試編碼，先刪除寫到一半的舊檔案
        if os.path.exists(output_file_path):
            os.remove(output_file_path)

        has_txo = False
        first_chunk = True

        with z_file.open(file_name) as f:
            chunk_iter = pd.read_csv(f, encoding=encoding, low_memory=False, chunksize=500000)
            for chunk in chunk_iter:
                chunk.columns = chunk.columns.str.strip()

                # 尋找 TXO 資料
                if '商品代碼' in chunk.columns:
                    filtered_chunk = chunk[chunk['商品代碼'].astype(str).str.strip() == 'TXO']
                elif '契約' in chunk.columns:
                    filtered_chunk = chunk[chunk['契約'].astype(str).str.strip() == 'TXO']
                else:
                    filtered_chunk = chunk[chunk.iloc[:, 0].astype(str).str.strip() == 'TXO']

                # 寫入檔案
                if not filtered_chunk.empty:
                    has_txo = True
                    filtered_chunk.to_csv(output_file_path, mode='a', header=first_chunk, index=False, encoding='utf-8-sig')
                    first_chunk = False

    try:
        # 期交所的資料 99% 是 cp950 (Big5)
        process_chunks('cp950')
    except UnicodeDecodeError:
        # 如果失敗，備用方案改用 utf-8
        process_chunks('utf-8-sig')

    return has_txo

# 4. 開始執行雙層解壓縮與過濾
print(f"🚀 開始讀取大型壓縮檔 {zip_path}...")
saved_files_count = 0

with zipfile.ZipFile(zip_path, 'r') as outer_z:
    # 取得外層的所有檔案 (排除 Mac 隱藏檔)
    target_files = [f for f in outer_z.namelist() if not f.endswith('/') and '__MACOSX' not in f]
    print(f"📦 偵測到 {len(target_files)} 個原始壓縮檔，開始執行「雙層解壓與過濾」...")

    for file_name in target_files:
        try:
            # 狀況 A：如果裡面包的是 .zip 檔案 (ZIP 包 ZIP)
            if file_name.lower().endswith('.zip'):
                # 將內層 ZIP 讀入記憶體 (不佔用雲端硬碟空間)
                inner_zip_bytes = outer_z.read(file_name)

                with zipfile.ZipFile(io.BytesIO(inner_zip_bytes), 'r') as inner_z:
                    inner_files = [f for f in inner_z.namelist() if not f.endswith('/') and '__MACOSX' not in f]

                    for inner_file in inner_files:
                        # 準備輸出檔名
                        out_name = os.path.basename(inner_file)
                        if not out_name.lower().endswith('.csv'):
                            out_name += '.csv'
                        out_path = os.path.join(output_folder, out_name)

                        # 執行過濾
                        if process_csv_file(inner_z, inner_file, out_path):
                            saved_files_count += 1
                            if saved_files_count % 10 == 0:
                                print(f"✅ 已成功產出 {saved_files_count} 個每日 TXO 檔案...")

            # 狀況 B：如果裡面直接就是 .csv 檔案
            else:
                out_name = os.path.basename(file_name)
                if not out_name.lower().endswith('.csv'):
                    out_name += '.csv'
                out_path = os.path.join(output_folder, out_name)

                if process_csv_file(outer_z, file_name, out_path):
                    saved_files_count += 1
                    if saved_files_count % 10 == 0:
                        print(f"✅ 已成功產出 {saved_files_count} 個每日 TXO 檔案...")

        except Exception as e:
            print(f"❌ 處理 {file_name} 時發生錯誤: {e}")

print(f"\n🎉 大功告成！完美解決 ZIP 雙層壓縮問題。")
print(f"📊 總共成功產出了 {saved_files_count} 個每日 TXO 獨立 CSV 檔。")
print(f"📂 檔案已安全放置於：{output_folder} 資料夾中！")

import zipfile
import pandas as pd
import os
import io
from google.colab import drive

# 1. 掛載雲端硬碟
if not os.path.exists('/content/drive'):
    drive.mount('/content/drive')

zip_path = '/content/drive/MyDrive/Option_2022.zip'
output_folder = '/content/drive/MyDrive/TXO_2022_Daily'

if not os.path.exists(output_folder):
    os.makedirs(output_folder)
    print(f"📁 已建立輸出資料夾：{output_folder}")

# 紀錄是否已經印過一次除錯資訊
debug_printed = False

# 2. 處理單一 CSV 檔案的核心函數 (加入自動偵測 TXO 欄位功能)
def process_csv_file(z_file, file_name, output_file_path):
    global debug_printed
    has_txo = False
    first_chunk = True

    def process_chunks(encoding):
        nonlocal has_txo, first_chunk
        global debug_printed

        if os.path.exists(output_file_path):
            os.remove(output_file_path)

        has_txo = False
        first_chunk = True

        with z_file.open(file_name) as f:
            # 每次讀取 20 萬筆
            chunk_iter = pd.read_csv(f, encoding=encoding, low_memory=False, chunksize=200000)

            for chunk in chunk_iter:
                chunk.columns = chunk.columns.str.strip()

                # 🕵️ 印出第一個檔案的實際欄位，讓我們知道長怎樣
                if not debug_printed:
                    print(f"\n🕵️ 【系統診斷】成功讀取資料！")
                    print(f"🔎 檔案內的實際欄位名稱為：\n{list(chunk.columns)}\n")
                    debug_printed = True

                # 🚀 AI 自動偵測：尋找哪一個欄位包含 'TXO'
                txo_col = None
                for col in chunk.columns:
                    # 使用 str.contains 模糊比對，避免被空白干擾
                    if chunk[col].astype(str).str.contains('TXO', na=False).any():
                        txo_col = col
                        break

                # 如果有找到包含 TXO 的欄位，就進行過濾
                if txo_col:
                    filtered_chunk = chunk[chunk[txo_col].astype(str).str.contains('TXO', na=False)]

                    if not filtered_chunk.empty:
                        has_txo = True
                        filtered_chunk.to_csv(output_file_path, mode='a', header=first_chunk, index=False, encoding='utf-8-sig')
                        first_chunk = False

    try:
        process_chunks('cp950')
    except UnicodeDecodeError:
        process_chunks('utf-8-sig')

    return has_txo

# 3. 開始執行雙層解壓縮與過濾
print(f"🚀 開始讀取大型壓縮檔 {zip_path}，啟動【TXO自動雷達偵測】...")
saved_files_count = 0

with zipfile.ZipFile(zip_path, 'r') as outer_z:
    target_files = [f for f in outer_z.namelist() if not f.endswith('/') and '__MACOSX' not in f]
    print(f"📦 偵測到 {len(target_files)} 個原始壓縮檔，開始處理...")

    for file_name in target_files:
        try:
            if file_name.lower().endswith('.zip'):
                inner_zip_bytes = outer_z.read(file_name)
                with zipfile.ZipFile(io.BytesIO(inner_zip_bytes), 'r') as inner_z:
                    inner_files = [f for f in inner_z.namelist() if not f.endswith('/') and '__MACOSX' not in f]

                    for inner_file in inner_files:
                        out_name = os.path.basename(inner_file)
                        if not out_name.lower().endswith('.csv'): out_name += '.csv'
                        out_path = os.path.join(output_folder, out_name)

                        if process_csv_file(inner_z, inner_file, out_path):
                            saved_files_count += 1
                            if saved_files_count % 20 == 0:
                                print(f"✅ 已成功產出 {saved_files_count} 個每日 TXO 檔案...")

            else:
                out_name = os.path.basename(file_name)
                if not out_name.lower().endswith('.csv'): out_name += '.csv'
                out_path = os.path.join(output_folder, out_name)

                if process_csv_file(outer_z, file_name, out_path):
                    saved_files_count += 1
                    if saved_files_count % 20 == 0:
                        print(f"✅ 已成功產出 {saved_files_count} 個每日 TXO 檔案...")

        except Exception as e:
            pass # 靜默略過非資料檔

print(f"\n🎉 大功告成！")
print(f"📊 總共成功產出了 {saved_files_count} 個每日 TXO 獨立 CSV 檔。")

import pandas as pd
import numpy as np
from scipy.stats import norm
import os
import chardet

# ==========================================
# 1. 參數與路徑設定
# ==========================================
YEAR = '2022'
INDEX_FILE_PATH = '/content/drive/MyDrive/Index_411336017_2022.csv'
DAILY_FOLDER_PATH = '/content/drive/MyDrive/TXO_2022_Daily'
OUTPUT_IV_FILE = f'/content/drive/MyDrive/{YEAR}_TXO_IV_Details.csv'
OUTPUT_STATS_FILE = f'/content/drive/MyDrive/{YEAR}_TXO_Daily_Stats_PCR.csv'

# ==========================================
# 2. Black-Scholes 模型與二分法
# ==========================================
def bs_price(S, K, T, r, sigma, cp_flag):
    if T <= 0 or sigma <= 0:
        return np.nan
    d1 = (np.log(S / K) + (r + 0.5 * sigma ** 2) * T) / (sigma * np.sqrt(T))
    d2 = d1 - sigma * np.sqrt(T)
    if cp_flag == 'C':
        return S * norm.cdf(d1) - K * np.exp(-r * T) * norm.cdf(d2)
    else:
        return K * np.exp(-r * T) * norm.cdf(-d2) - S * norm.cdf(-d1)

def calculate_iv_bisection(market_price, S, K, T, r, cp_flag, tol=1e-5, max_iter=100):
    if T <= 0:
        return np.nan
    if pd.isna(market_price) or pd.isna(S) or pd.isna(K) or pd.isna(r) or market_price <= 0:
        return np.nan
    low, high = 1e-4, 5.0
    for _ in range(max_iter):
        mid = (low + high) / 2
        price_mid = bs_price(S, K, T, r, mid, cp_flag)
        if pd.isna(price_mid):
            return np.nan
        if abs(price_mid - market_price) < tol:
            return mid
        if price_mid < market_price:
            low = mid
        else:
            high = mid
    return (low + high) / 2

# ==========================================
# 3. 檔案讀取輔助函數
# ==========================================
def read_csv_safely(file_path):
    try:
        return pd.read_csv(file_path, encoding='utf-8-sig', low_memory=False)
    except UnicodeDecodeError:
        try:
            return pd.read_csv(file_path, encoding='cp950', low_memory=False)
        except UnicodeDecodeError:
            with open(file_path, 'rb') as f:
                result = chardet.detect(f.read(100000))
            return pd.read_csv(file_path, encoding=result['encoding'], low_memory=False)

# ==========================================
# 4. 主程式處理邏輯
# ==========================================
def main():
    print("🚀 開始讀取索引檔並處理每日 IV...")
    index_df = pd.read_csv(INDEX_FILE_PATH)

    all_iv_details = []
    daily_stats = []

    for idx, row in index_df.iterrows():
        date = row['Date']
        file_name = row['File']
        S0 = row['S0']
        maturity_days = row['Maturity']
        Rf = row['Rf']

        # 【新增條件 1】：距離到期天數 (Maturity) 必須大於 30 天才採用
        # (若你的意思是別的條件，可以將這三行註解掉)
        if maturity_days <= 30:
            print(f"⏩ {date} 距離到期天數僅 {maturity_days} 天 (<=30)，跳過不採用。")
            continue

        T = maturity_days / 365.0

        file_path = os.path.join(DAILY_FOLDER_PATH, file_name)
        if not os.path.exists(file_path):
            print(f"⚠️ 找不到檔案，已略過：{file_name}")
            continue

        daily_df = read_csv_safely(file_path)

        daily_df.columns = daily_df.columns.str.strip()
        if '成交日期' in daily_df.columns:
            daily_df = daily_df[~daily_df['成交日期'].astype(str).str.contains('--', na=False)]

        vol_col = next((col for col in daily_df.columns if '成交數量' in col), None)
        if not vol_col:
            continue

        daily_df[vol_col] = pd.to_numeric(daily_df[vol_col].astype(str).str.replace(r'[^\d.]', '', regex=True), errors='coerce')
        daily_df['履約價'] = pd.to_numeric(daily_df['履約價'], errors='coerce')
        daily_df['成交價'] = pd.to_numeric(daily_df['成交價'], errors='coerce')

        daily_df['買賣權別'] = daily_df['買賣權別'].astype(str).str.strip().str.upper()
        daily_df['買賣權別'] = daily_df['買賣權別'].apply(lambda x: 'C' if 'C' in x or '買' in x else ('P' if 'P' in x or '賣' in x else x))

        # 計算全市場 PCR (不套用成交量過濾條件)
        call_vol_total = daily_df[daily_df['買賣權別'] == 'C'][vol_col].sum()
        put_vol_total = daily_df[daily_df['買賣權別'] == 'P'][vol_col].sum()
        pcr = put_vol_total / call_vol_total if call_vol_total > 0 else np.nan

        # 【新增條件 2】：嚴格過濾成交數量 > 30 (原本是 >= 30)
        filtered_df = daily_df[daily_df[vol_col] > 30].copy()

        # 額外補充：如果你說的「成交日 > 30」是指「成交價 (Premium) > 30」，請解除下面這行的註解
        # filtered_df = filtered_df[filtered_df['成交價'] > 30]

        if filtered_df.empty:
            continue

        filtered_df['IV'] = filtered_df.apply(
            lambda x: calculate_iv_bisection(
                market_price=x['成交價'], S=S0, K=x['履約價'], T=T, r=Rf, cp_flag=x['買賣權別']
            ), axis=1
        )

        filtered_df = filtered_df.dropna(subset=['IV'])

        filtered_df['Date'] = date
        filtered_df['S0'] = S0
        filtered_df['Maturity'] = maturity_days
        filtered_df['Rf'] = Rf

        cols_to_keep = ['Date', '買賣權別', '履約價', '成交價', vol_col, 'IV', 'S0', 'Maturity', 'Rf']
        cols_to_keep = [c for c in cols_to_keep if c in filtered_df.columns]

        all_iv_details.append(filtered_df[cols_to_keep].rename(columns={vol_col: '成交量'}))

        call_ivs = filtered_df[filtered_df['買賣權別'] == 'C']['IV']
        put_ivs = filtered_df[filtered_df['買賣權別'] == 'P']['IV']

        daily_stats.append({
            'Date': date,
            'PCR': pcr,
            'Call IV 平均': call_ivs.mean() if not call_ivs.empty else np.nan,
            'Call IV 樣本標準差': call_ivs.std(ddof=1) if len(call_ivs) > 1 else np.nan,
            'Put IV 平均': put_ivs.mean() if not put_ivs.empty else np.nan,
            'Put IV 樣本標準差': put_ivs.std(ddof=1) if len(put_ivs) > 1 else np.nan
        })

        if (idx + 1) % 20 ==

import pandas as pd
import numpy as np
from scipy.stats import norm
import os
import chardet

# ==========================================
# 1. 參數與路徑設定 (請確保路徑符合你的雲端硬碟配置)
# ==========================================
YEAR = '2022'
INDEX_FILE_PATH = '/content/drive/MyDrive/Index_411336017_2022.csv'
DAILY_FOLDER_PATH = '/content/drive/MyDrive/TXO_2022_Daily'
OUTPUT_IV_FILE = f'/content/drive/MyDrive/{YEAR}_TXO_IV_Details.csv'
OUTPUT_STATS_FILE = f'/content/drive/MyDrive/{YEAR}_TXO_Daily_Stats_PCR.csv'

# ==========================================
# 2. Black-Scholes 模型與二分法
# ==========================================
def bs_price(S, K, T, r, sigma, cp_flag):
    """計算 Black-Scholes 理論價"""
    # 【極重要防呆】若 T<=0 則分母會有 sqrt(0) 導致 zero division，直接回傳 NaN
    if T <= 0 or sigma <= 0:
        return np.nan

    d1 = (np.log(S / K) + (r + 0.5 * sigma ** 2) * T) / (sigma * np.sqrt(T))
    d2 = d1 - sigma * np.sqrt(T)

    if cp_flag == 'C':
        return S * norm.cdf(d1) - K * np.exp(-r * T) * norm.cdf(d2)
    else:
        return K * np.exp(-r * T) * norm.cdf(-d2) - S * norm.cdf(-d1)

def calculate_iv_bisection(market_price, S, K, T, r, cp_flag, tol=1e-5, max_iter=100):
    """利用二分法反推隱含波動率 (IV)"""
    if T <= 0:
        return np.nan
    if pd.isna(market_price) or pd.isna(S) or pd.isna(K) or pd.isna(r) or market_price <= 0:
        return np.nan

    low, high = 1e-4, 5.0 # 設定 IV 搜尋範圍 0.01% ~ 500%

    for _ in range(max_iter):
        mid = (low + high) / 2
        price_mid = bs_price(S, K, T, r, mid, cp_flag)

        if pd.isna(price_mid):
            return np.nan

        if abs(price_mid - market_price) < tol:
            return mid

        if price_mid < market_price:
            low = mid
        else:
            high = mid

    return (low + high) / 2

# ==========================================
# 3. 檔案讀取輔助函數 (自動偵測編碼)
# ==========================================
def read_csv_safely(file_path):
    """自動偵測編碼讀取檔案，解決 UnicodeDecodeError"""
    try:
        return pd.read_csv(file_path, encoding='utf-8-sig', low_memory=False)
    except UnicodeDecodeError:
        try:
            return pd.read_csv(file_path, encoding='cp950', low_memory=False)
        except UnicodeDecodeError:
            with open(file_path, 'rb') as f:
                result = chardet.detect(f.read(100000))
            return pd.read_csv(file_path, encoding=result['encoding'], low_memory=False)

# ==========================================
# 4. 主程式處理邏輯
# ==========================================
def main():
    print("🚀 開始讀取 2022 索引檔並處理每日 IV...")
    index_df = pd.read_csv(INDEX_FILE_PATH)

    all_iv_details = []
    daily_stats = []

    for idx, row in index_df.iterrows():
        date = row['Date']
        file_name = row['File']
        S0 = row['S0']
        maturity_days = row['Maturity']
        Rf = row['Rf']

        # 【重要】將天數年化
        T = maturity_days / 365.0

        file_path = os.path.join(DAILY_FOLDER_PATH, file_name)
        if not os.path.exists(file_path):
            print(f"⚠️ 找不到檔案，已略過：{file_name}")
            continue

        daily_df = read_csv_safely(file_path)

        # 資料清洗：去除所有欄位名稱的前後空白
        daily_df.columns = daily_df.columns.str.strip()

        # 動態鎖定「成交數量」相關的欄位 (可能是 '成交數量' 或 '成交數量(B or S)')
        vol_col = next((col for col in daily_df.columns if '成交數量' in col), None)
        if not vol_col:
            continue

        # 數值清洗：移除可能的逗號或雜訊，轉換為數值型態
        daily_df[vol_col] = pd.to_numeric(daily_df[vol_col].astype(str).str.replace(r'[^\d.]', '', regex=True), errors='coerce')
        daily_df['履約價'] = pd.to_numeric(daily_df['履約價'], errors='coerce')
        daily_df['成交價'] = pd.to_numeric(daily_df['成交價'], errors='coerce')

        # 買賣權別標準化
        daily_df['買賣權別'] = daily_df['買賣權別'].astype(str).str.strip().str.upper()
        daily_df['買賣權別'] = daily_df['買賣權別'].apply(lambda x: 'C' if 'C' in x or '買' in x else ('P' if 'P' in x or '賣' in x else x))

        # 計算 PCR (不受成交量大於30的限制)
        call_vol_total = daily_df[daily_df['買賣權別'] == 'C'][vol_col].sum()
        put_vol_total = daily_df[daily_df['買賣權別'] == 'P'][vol_col].sum()
        pcr = put_vol_total / call_vol_total if call_vol_total > 0 else np.nan

        # 【重要條件】：嚴格篩選成交量 > 30 的資料才算 IV
        filtered_df = daily_df[daily_df[vol_col] > 30].copy()

        if filtered_df.empty:
            continue

        # 逐筆計算 IV
        filtered_df['IV'] = filtered_df.apply(
            lambda x: calculate_iv_bisection(
                market_price=x['成交價'], S=S0, K=x['履約價'], T=T, r=Rf, cp_flag=x['買賣權別']
            ), axis=1
        )

        # 移除算不出 IV 的列 (例如結算日 T=0 的資料)
        filtered_df = filtered_df.dropna(subset=['IV'])

        # 標註每日環境變數
        filtered_df['Date'] = date
        filtered_df['S0'] = S0
        filtered_df['Maturity'] = maturity_days
        filtered_df['Rf'] = Rf

        cols_to_keep = ['Date', '買賣權別', '履約價', '成交價', vol_col, 'IV', 'S0', 'Maturity', 'Rf']
        cols_to_keep = [c for c in cols_to_keep if c in filtered_df.columns]

        all_iv_details.append(filtered_df[cols_to_keep].rename(columns={vol_col: '成交量'}))

        # 敘述性統計：計算平均與樣本標準差 (ddof=1)
        call_ivs = filtered_df[filtered_df['買賣權別'] == 'C']['IV']
        put_ivs = filtered_df[filtered_df['買賣權別'] == 'P']['IV']

        daily_stats.append({
            'Date': date,
            'PCR': pcr,
            'Call IV 平均': call_ivs.mean() if not call_ivs.empty else np.nan,
            'Call IV 樣本標準差': call_ivs.std(ddof=1) if len(call_ivs) > 1 else np.nan,
            'Put IV 平均': put_ivs.mean() if not put_ivs.empty else np.nan,
            'Put IV 樣本標準差': put_ivs.std(ddof=1) if len(put_ivs) > 1 else np.nan
        })

        if (idx + 1) % 20 == 0:
            print(f"✅ 已處理 {idx + 1} 個交易日...")

    # ==========================================
    # 5. 匯出成果
    # ==========================================
    print("\n📦 準備匯出資料...")
    if all_iv_details:
        final_details_df = pd.concat(all_iv_details, ignore_index=True)
        final_stats_df = pd.DataFrame(daily_stats)

        final_details_df.to_csv(OUTPUT_IV_FILE, index=False, encoding='utf-8-sig')
        final_stats_df.to_csv(OUTPUT_STATS_FILE, index=False, encoding='utf-8-sig')

        print(f"🎉 大功告成！檔案已儲存：\n1. {OUTPUT_IV_FILE}\n2. {OUTPUT_STATS_FILE}")
    else:
        print("⚠️ 沒有產出任何有效資料，請檢查路徑或資料內容。")

if __name__ == "__main__":
    main()

# ==========================================
# 1. 掛載雲端硬碟與匯入套件
# ==========================================
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import math
import chardet
import os

# ==========================================
# 2. 路徑設定 (已更新為 2022 年度路徑)
# ==========================================
# 使用你上傳的 2022 索引檔名
INDEX_FILE_PATH = '/content/drive/MyDrive/Index_411336017_2022.csv'

# 存放你 2022 每日 TXO 資料的資料夾 (請確認資料夾名稱是否正確)
TXO_DAILY_DIR = '/content/drive/MyDrive/TXO_2022_Daily/'

# 最終輸出的兩個檔案路徑
OUTPUT_CLEAN_DATA = '/content/drive/MyDrive/2022_TXO_IV_Details.csv'
OUTPUT_STATISTICS = '/content/drive/MyDrive/2022_TXO_Daily_Stats_PCR.csv'

# ==========================================
# 3. 核心函數：Black-Scholes 與二分法 (含關鍵防呆)
# ==========================================
def fast_norm_cdf(x):
    """極速版常態分配累積機率函數"""
    return 0.5 * (1.0 + math.erf(x / math.sqrt(2.0)))

def bs_price(cp_flag, S, K, T, r, sigma):
    """計算 Black-Scholes 價格"""
    # 【核心防呆】處理老師提到的 T=365 年化問題。
    # 如果 T <= 0 (結算日)，分母 sqrt(T) 會導致 float division by zero。
    if T <= 0 or sigma <= 0:
        return 0

    d1 = (math.log(S / K) + (r + 0.5 * sigma**2) * T) / (sigma * math.sqrt(T))
    d2 = d1 - sigma * math.sqrt(T)

    if cp_flag == 'C':
        return S * fast_norm_cdf(d1) - K * math.exp(-r * T) * fast_norm_cdf(d2)
    else: # Put
        return K * math.exp(-r * T) * fast_norm_cdf(-d2) - S * fast_norm_cdf(-d1)

def find_iv_bisection(cp_flag, market_price, S, K, T, r, tol=1e-6, max_iter=100):
    """使用二分法反推隱含波動率 (IV)"""
    # 【核心防呆】結算日當天無法計算 IV，直接回傳 NaN 避開錯誤
    if T <= 0:
        return float('nan')

    low = 0.0001
    high = 5.0 # 搜尋上限 500%

    # 檢查基本的套利邊界，不符合則不計算 IV
    if cp_flag == 'C':
        if market_price <= 0 or market_price < (S - K * math.exp(-r * T)): return float('nan')
    else: # Put
        if market_price <= 0 or market_price < (K * math.exp(-r * T) - S): return float('nan')

    for _ in range(max_iter):
        mid = (low + high) / 2.0
        price = bs_price(cp_flag, S, K, T, r, mid)
        if abs(price - market_price) < tol: return mid
        if price < market_price: low = mid
        else: high = mid
    return mid

# ==========================================
# 4. 讀取索引檔與主程式迴圈
# ==========================================
print("正在讀取 2022 索引檔...")
try:
    with open(INDEX_FILE_PATH, 'rb') as f:
        idx_enc = chardet.detect(f.read(10000))['encoding']
    index_df = pd.read_csv(INDEX_FILE_PATH, encoding=idx_enc, skipinitialspace=True)
    index_df.columns = index_df.columns.str.strip()
except FileNotFoundError:
    print(f"❌ 找不到索引檔：{INDEX_FILE_PATH}")
    raise

all_details = []
daily_stats_list = []

print("開始逐日處理 2022 資料...")

for _, row in index_df.iterrows():
    date_str = str(row['Date']).strip()
    file_name = str(row['File']).strip()
    S0 = float(row['S0'])

    # 【關鍵】年化處理 T = Maturity / 365
    T_years = float(row['Maturity']) / 365.0
    r = float(row['Rf'])

    target_file = os.path.join(TXO_DAILY_DIR, file_name)
    if not os.path.exists(target_file):
        # 嘗試補上 TXO_ 前綴的可能性
        target_file = os.path.join(TXO_DAILY_DIR, f"TXO_{file_name}")

    if not os.path.exists(target_file):
        print(f"  [警告] 找不到檔案 {file_name}，跳過該日。")
        continue

    try:
        with open(target_file, 'rb') as f:
            encoding = chardet.detect(f.read(10000))['encoding']
        daily_df = pd.read_csv(target_file, encoding=encoding, skipinitialspace=True, low_memory=False)
        daily_df.columns = daily_df.columns.str.strip()

        # 清除期中報告雜訊 (排除成交日期含有 '-' 的分隔線)
        if '成交日期' in daily_df.columns:
            daily_df = daily_df[~daily_df['成交日期'].astype(str).str.contains('-', na=False)]

        daily_df['買賣權別'] = daily_df['買賣權別'].astype(str).str.strip()

        # 處理「成交數量」欄位 (自動偵測不同名稱並清除空白)
        vol_col = '成交數量(B or S)' if '成交數量(B or S)' in daily_df.columns else '成交數量'
        daily_df[vol_col] = pd.to_numeric(daily_df[vol_col].astype(str).str.strip(), errors='coerce')

        # 只保留 TXO 商品
        if '商品代號' in daily_df.columns:
            daily_df['商品代號'] = daily_df['商品代號'].astype(str).str.strip()
            txo_df = daily_df[daily_df['商品代號'] == 'TXO'].copy()
        else:
            txo_df = daily_df.copy()

        # ==========================================
        # ★ 計算 PCR (全當日資料，不設成交量門檻)
        # ==========================================
        total_call_vol = txo_df[txo_df['買賣權別'].str.contains('C|買', na=False)][vol_col].sum()
        total_put_vol = txo_df[txo_df['買賣權別'].str.contains('P|賣', na=False)][vol_col].sum()
        pcr_value = total_put_vol / total_call_vol if total_call_vol > 0 else np.nan

        # ==========================================
        # ★ IV 計算前過濾：成交量 >= 30 (重要要求)
        # ==========================================
        iv_df = txo_df[txo_df[vol_col] >= 30].copy()

        if not iv_df.empty:
            # 欄位統一命名與轉換
            price_col = '成交價格' if '成交價格' in iv_df.columns else '成交價'
            strike_col = '履約價格' if '履約價格' in iv_df.columns else '履約價'

            iv_df[price_col] = pd.to_numeric(iv_df[price_col], errors='coerce')
            iv_df[strike_col] = pd.to_numeric(iv_df[strike_col], errors='coerce')
            iv_df = iv_df.dropna(subset=[price_col, strike_col])

            # 統一標籤 C / P
            iv_df['cp_tag'] = iv_df['買賣權別'].apply(lambda x: 'C' if 'C' in x or '買' in x else 'P')

            # 計算 IV
            iv_df['IV'] = iv_df.apply(
                lambda x: find_iv_bisection(x['cp_tag'], x[price_col], S0, x[strike_col], T_years, r), axis=1
            )

            # 移除 NaN (如結算日數據)
            iv_df = iv_df.dropna(subset=['IV'])

            # 儲存明細
            iv_df['Date'] = date_str
            iv_df['S0'] = S0
            iv_df['Maturity'] = row['Maturity']
            iv_df['Rf'] = r

            detail_cols = ['Date', '買賣權別', strike_col, price_col, vol_col, 'IV', 'S0', 'Maturity', 'Rf']
            all_details.append(iv_df[detail_cols])

            # ==========================================
            # ★ 敘述性統計 (樣本標準差 ddof=1)
            # ==========================================
            call_iv = iv_df[iv_df['cp_tag'] == 'C']['IV']
            put_iv = iv_df[iv_df['cp_tag'] == 'P']['IV']

            daily_stats_list.append({
                'Date': date_str,
                'PCR': pcr_value,
                'Call IV 平均': call_iv.mean(),
                'Call IV 樣本標準差': call_iv.std(ddof=1),
                'Put IV 平均': put_iv.mean(),
                'Put IV 樣本標準差': put_iv.std(ddof=1)
            })

            print(f"  ✅ {date_str} 處理完成 (Maturity: {row['Maturity']})")
        else:
            print(f"  [提示] {date_str} 無符合成交量 >= 30 之資料。")

    except Exception as e:
        print(f"  ❌ 處理 {date_str} 時出錯: {e}")

# ==========================================
# 5. 合併與匯出 2022 年度成果
# ==========================================
if all_details:
    final_details = pd.concat(all_details, ignore_index=True)
    final_details.to_csv(OUTPUT_CLEAN_DATA, index=False, encoding='utf-8-sig')

    stats_df = pd.DataFrame(daily_stats_list)
    stats_df.to_csv(OUTPUT_STATISTICS, index=False, encoding='utf-8-sig')

    print(f"\n🎉 2022 年度資料處理完畢！")
    print(f"📁 明細檔：{OUTPUT_CLEAN_DATA}")
    print(f"📊 統計檔：{OUTPUT_STATISTICS}")
else:
    print("\n❌ 處理失敗，請檢查資料夾路徑或檔案內容。")

# ==========================================
# 1. 掛載雲端硬碟與匯入套件
# ==========================================
from google.colab import drive
import pandas as pd
import numpy as np
import math
import chardet
import os

# 掛載雲端硬碟
drive.mount('/content/drive')

# ==========================================
# 2. 路徑設定 (請確認你的資料夾名稱正確)
# ==========================================
INDEX_FILE_PATH = '/content/drive/MyDrive/Index_411336017_2022.csv'
TXO_DAILY_DIR = '/content/drive/MyDrive/TXO_2022_Daily/' # 你的原始資料夾

# 輸出路徑 (會直接存回雲端硬碟)
OUTPUT_CLEAN_DATA = '/content/drive/MyDrive/2022_TXO_IV_Details.csv'
OUTPUT_STATISTICS = '/content/drive/MyDrive/2022_TXO_Daily_Stats_PCR.csv'

# ==========================================
# 3. 核心函數定義 (放在同一個 Cell 避免 NameError)
# ==========================================
def fast_norm_cdf(x):
    return 0.5 * (1.0 + math.erf(x / math.sqrt(2.0)))

def bs_price(cp_flag, S, K, T, r, sigma):
    if T <= 0 or sigma <= 0: return 0
    d1 = (math.log(S / K) + (r + 0.5 * sigma**2) * T) / (sigma * math.sqrt(T))
    d2 = d1 - sigma * math.sqrt(T)
    if cp_flag == 'C':
        return S * fast_norm_cdf(d1) - K * math.exp(-r * T) * fast_norm_cdf(d2)
    else:
        return K * math.exp(-r * T) * fast_norm_cdf(-d2) - S * fast_norm_cdf(-d1)

def find_iv_bisection(cp_flag, market_price, S, K, T, r, tol=1e-6, max_iter=100):
    if T <= 0: return float('nan')
    low, high = 0.0001, 5.0
    # 套利邊界檢查
    if cp_flag == 'C':
        if market_price <= 0 or market_price < (S - K * math.exp(-r * T)): return float('nan')
    else:
        if market_price <= 0 or market_price < (K * math.exp(-r * T) - S): return float('nan')

    for _ in range(max_iter):
        mid = (low + high) / 2.0
        price = bs_price(cp_flag, S, K, T, r, mid)
        if abs(price - market_price) < tol: return mid
        if price < market_price: low = mid
        else: high = mid
    return mid

# ==========================================
# 4. 主程式：讀取、計算、過濾、統計
# ==========================================
print("🚀 開始處理 2022 年度資料...")

# 讀取索引檔
with open(INDEX_FILE_PATH, 'rb') as f:
    idx_enc = chardet.detect(f.read(10000))['encoding']
index_df = pd.read_csv(INDEX_FILE_PATH, encoding=idx_enc)
index_df.columns = index_df.columns.str.strip()

all_details = []
daily_stats_list = []

for _, row in index_df.iterrows():
    date_str = str(row['Date']).strip()
    file_name = str(row['File']).strip()
    S0, r = float(row['S0']), float(row['Rf'])
    T_years = float(row['Maturity']) / 365.0 # 年化天數

    target_file = os.path.join(TXO_DAILY_DIR, file_name)
    if not os.path.exists(target_file):
        continue

    try:
        # 讀取每日檔案
        with open(target_file, 'rb') as f:
            encoding = chardet.detect(f.read(10000))['encoding']
        daily_df = pd.read_csv(target_file, encoding=encoding, low_memory=False)
        daily_df.columns = daily_df.columns.str.strip()

        # 資料清洗
        if '成交日期' in daily_df.columns:
            daily_df = daily_df[~daily_df['成交日期'].astype(str).str.contains('-', na=False)]

        vol_col = '成交數量(B or S)' if '成交數量(B or S)' in daily_df.columns else '成交數量'
        daily_df[vol_col] = pd.to_numeric(daily_df[vol_col].astype(str).str.strip(), errors='coerce')

        # 統一 Call/Put 標籤
        daily_df['cp_tag'] = daily_df['買賣權別'].astype(str).str.strip().apply(lambda x: 'C' if 'C' in x or '買' in x else 'P')

        # 1. 計算全日 PCR
        total_call_v = daily_df[daily_df['cp_tag'] == 'C'][vol_col].sum()
        total_put_v = daily_df[daily_df['cp_tag'] == 'P'][vol_col].sum()
        pcr_value = total_put_v / total_call_v if total_call_v > 0 else np.nan

        # 2. 條件過濾：成交量 > 30 且成交日 > 30 (若是指價格)
        # 這裡根據你的要求：成交量 > 30
        iv_df = daily_df[daily_df[vol_col] > 30].copy()

        if not iv_df.empty:
            price_col = '成交價格' if '成交價格' in iv_df.columns else '成交價'
            strike_col = '履約價格' if '履約價格' in iv_df.columns else '履約價'

            iv_df[price_col] = pd.to_numeric(iv_df[price_col], errors='coerce')
            iv_df[strike_col] = pd.to_numeric(iv_df[strike_col], errors='coerce')
            iv_df = iv_df.dropna(subset=[price_col, strike_col])

            # 計算 IV
            iv_df['IV'] = iv_df.apply(
                lambda x: find_iv_bisection(x['cp_tag'], x[price_col], S0, x[strike_col], T_years, r), axis=1
            )
            iv_df = iv_df.dropna(subset=['IV'])

            # 存入明細清單
            iv_df['Date'] = date_str
            all_details.append(iv_df[['Date', '買賣權別', strike_col, price_col, vol_col, 'IV']])

            # 3. 敘述性統計 (依照你指定的圖一標題)
            call_iv = iv_df[iv_df['cp_tag'] == 'C']['IV']
            put_iv = iv_df[iv_df['cp_tag'] == 'P']['IV']

            daily_stats_list.append({
                'Date': date_str,
                'PCR': pcr_value,
                '看漲(Call) IV 平均值': call_iv.mean(),
                '看漲(Call) IV 樣本標準差': call_iv.std(ddof=1),
                '看跌(Put) IV 平均值': put_iv.mean(),
                '看跌(Put) IV 樣本標準差': put_iv.std(ddof=1)
            })
            print(f" ✅ {date_str} 完成")

    except Exception as e:
        print(f" ❌ {date_str} 出錯: {e}")

# ==========================================
# 5. 存回雲端硬碟
# ==========================================
if all_details:
    pd.concat(all_details).to_csv(OUTPUT_CLEAN_DATA, index=False, encoding='utf-8-sig')
    pd.DataFrame(daily_stats_list).to_csv(OUTPUT_STATISTICS, index=False, encoding='utf-8-sig')
    print(f"\n✨ 任務完成！檔案已回存至雲端：\n1. {OUTPUT_CLEAN_DATA}\n2. {OUTPUT_STATISTICS}")