# -*- coding: utf-8 -*-
"""Process_411236006_2021.

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y7hveIgPPHvmi4K0txL3mss78Dngg_nj
"""

import pandas as pd
import numpy as np
from scipy.stats import norm
import os
from google.colab import drive

# =================================================================
# 1. 環境設定與資料準備
# =================================================================
drive.mount('/content/drive', force_remount=True)

index_file_path = '/content/drive/MyDrive/金融資料探勘/期中/期中索引檔.csv '
data_base_path = '/content/Option_2021'
output_base_path = '/content/drive/MyDrive/金融資料探勘/期中/'

if not os.path.exists(data_base_path):
    print("正在解壓縮 Option_2021.zip...")
    !unzip -n -q /content/Option_2021.zip -d /content/
    print("解壓縮完成！")

# =================================================================
# 2. Black-Scholes 模型函數
# =================================================================
def bs_price(S, K, T, r, sigma, cp_flag):
    if T <= 0 or sigma <= 0:
        return max(0.0, S - K) if cp_flag == 'C' else max(0.0, K - S)
    d1 = (np.log(S / K) + (r + 0.5 * sigma**2) * T) / (sigma * np.sqrt(T))
    d2 = d1 - sigma * np.sqrt(T)
    if cp_flag == 'C':
        return S * norm.cdf(d1) - K * np.exp(-r * T) * norm.cdf(d2)
    else:
        return K * np.exp(-r * T) * norm.cdf(-d2) - S * norm.cdf(-d1)

def find_iv_combined(market_price, S, K, T, r, cp_flag):
    intrinsic_val = max(0, S - K) if cp_flag == 'C' else max(0, K - S)
    if market_price <= intrinsic_val: return 0.0
    low, high = 0.0001, 5.0
    for _ in range(100):
        mid = (low + high) / 2
        price = bs_price(S, K, T, r, mid, cp_flag)
        if abs(market_price - price) < 1e-5: return mid
        if price < market_price: low = mid
        else: high = mid
    return mid

# =================================================================
# 3. 主程式：整合計算 Call/Put/PCR 與 IV 統計
# =================================================================
print("\n--- 開始執行全年度資料分析 (含 IV 標準差統計) ---")

try:
    df_index = pd.read_csv(index_file_path, encoding='utf-8-sig')
except:
    df_index = pd.read_csv(index_file_path, encoding='cp950')

df_index.columns = df_index.columns.str.strip()
summary_list = []

for index, row in df_index.iterrows():
    date_str = pd.to_datetime(row['Date']).strftime('%Y%m%d')
    file_name = f"o{date_str}.csv"
    file_path = os.path.join(data_base_path, file_name)
    target_contract = str(row['Contract']).split('.')[0].strip()
    S0, rf, T = float(row['S0']), float(row['Rf']), float(row['Maturity'])/365.0

    if os.path.exists(file_path):
        try:
            try:
                df = pd.read_csv(file_path, encoding='utf-8-sig', low_memory=False)
            except:
                df = pd.read_csv(file_path, encoding='cp950', low_memory=False)

            df.columns = df.columns.str.replace(r'\s+', '', regex=True)
            for c in ['成交數量(BorS)', '履約價格', '成交價格']:
                df[c] = pd.to_numeric(df[c], errors='coerce')

            df['商品代號'] = df['商品代號'].astype(str).str.strip()
            df['買賣權別'] = df['買賣權別'].astype(str).str.strip().str.upper()
            df['到期月份(週別)'] = df['到期月份(週別)'].astype(str).str.split('.').str[0].str.strip()

            base_mask = (df['商品代號'] == 'TXO') & (df['成交數量(BorS)'] > 30) & \
                        (df['到期月份(週別)'] == target_contract) & (df['成交價格'] > 0)

            # 分別提取資料
            c_df = df[base_mask & df['買賣權別'].str.contains('C|買')].copy()
            p_df = df[base_mask & df['買賣權別'].str.contains('P|賣')].copy()

            # 計算 IV
            c_iv = c_df.apply(lambda x: find_iv_combined(x['成交價格'], S0, x['履約價格'], T, rf, 'C'), axis=1) if not c_df.empty else pd.Series(dtype=float)
            p_iv = p_df.apply(lambda x: find_iv_combined(x['成交價格'], S0, x['履約價格'], T, rf, 'P'), axis=1) if not p_df.empty else pd.Series(dtype=float)

            # 統計數值
            c_vol, p_vol = c_df['成交數量(BorS)'].sum(), p_df['成交數量(BorS)'].sum()

            summary_list.append({
                'Date': row['Date'],
                'S0': S0,
                'Call_Vol': c_vol,
                'Put_Vol': p_vol,
                'PCR': p_vol / c_vol if c_vol > 0 else np.nan,
                # Call IV 統計
                'Call_IV_Mean': c_iv.mean(),
                'Call_IV_Std': c_iv.std(),  # 標準差
                'Call_IV_Weighted': np.average(c_iv, weights=c_df['成交數量(BorS)']) if not c_iv.empty else np.nan,
                # Put IV 統計
                'Put_IV_Mean': p_iv.mean(),
                'Put_IV_Std': p_iv.std(),   # 標準差
                'Put_IV_Weighted': np.average(p_iv, weights=p_df['成交數量(BorS)']) if not p_iv.empty else np.nan
            })
            print(f"處理完成: {date_str}")
        except Exception as e:
            print(f"跳過 {date_str}，錯誤: {e}")
    else:
        print(f"跳過 {date_str} (檔案不存在)")

# =================================================================
# 4. 產出報表
# =================================================================
final_df = pd.DataFrame(summary_list)
output_path = os.path.join(output_base_path, 'TXO_2021_Full_Statistics_Report.csv')
final_df.to_csv(output_path, index=False, encoding='utf-8-sig')

print(f"\n✨ 包含 IV 標準差的統計報表已產出：{output_path}")