# -*- coding: utf-8 -*-
"""2022作業411336004

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RR6YpNNcNvZB5MWoid5-Akho05GqAucQ
"""

import pandas as pd

# 1. 讀取 Excel 檔案
file_path = '活頁簿1.xlsx'
df = pd.read_excel(file_path)

# 2. 清除欄位名稱前後的空白字元
df.columns = df.columns.str.strip()

# 3. 欄位重新命名對照表 (將您的 Excel 標題對齊到 Path_0305 的格式)
# 如果您的 Excel 裡標的價格不叫 'S0'，請在下方字典加入對應名稱
rename_dict = {
    '年月日': 'Date',
    '標的價格': 'S0',
    '收盤價': 'S0',
    '收盤指數': 'S0'
}
df = df.rename(columns=rename_dict)

# 檢查是否成功更名，若仍無 S0，則強制將第 3 個欄位當作 S0 (假設位置固定)
if 'S0' not in df.columns:
    print(f"警告：找不到名為 'S0' 的欄位，嘗試將原始第 3 欄 {df.columns[2]} 視為 S0")
    df = df.rename(columns={df.columns[2]: 'S0'})

# 4. 處理 Date 格式與生成 File 欄位
# 確保 Date 存在
if 'Date' in df.columns:
    df['Date_obj'] = pd.to_datetime(df['Date'])

    # 生成 File 內容 (例如：OptionsDaily_2022_01_03.csv)
    df['File'] = df['Date_obj'].dt.strftime('OptionsDaily_%Y_%m_%d.csv')

    # 格式化 Date 顯示方式為 YYYY/M/D
    df['Date'] = df['Date_obj'].dt.strftime('%Y/%-m/%-d')
else:
    print("錯誤：找不到日期相關欄位，請檢查 Excel 第一列是否有 '年月日' 或 'Date'")

# 5. 確保 Date, File, S0 都存在後才進行選取
try:
    df_final = df[['Date', 'File', 'S0']]

    # 6. 輸出結果與儲存
    print("--- 欄位對齊成功！前 5 筆如下 ---")
    print(df_final.head())

    output_name = 'Path_活頁簿1_Final.csv'
    df_final.to_csv(output_name, index=False, encoding='utf-8-sig')
    print(f"\n檔案已儲存為: {output_name}")

except KeyError as e:
    print(f"處理失敗：{e}")
    print(f"目前檔案中的實際欄位名稱為：{list(df.columns)}")

import pandas as pd

# 1. 讀取資料
file_name = 'Path_Result_246.csv'
df = pd.read_csv(file_name)

# 2. 轉換日期格式以便進行區間比較
df['Date_tmp'] = pd.to_datetime(df['Date'])

# 3. 定義 2022 年 Rf (一年期定儲機動利率) 的變動邏輯
def get_rf(date):
    # 2022/03/21 升息
    if date < pd.Timestamp('2022-03-21'):
        return 0.840
    # 2022/06/21 升息
    elif date < pd.Timestamp('2022-06-21'):
        return 1.090
    # 2022/09/26 升息
    elif date < pd.Timestamp('2022-09-26'):
        return 1.215
    # 2022/12/19 升息
    elif date < pd.Timestamp('2022-12-19'):
        return 1.340
    # 2022/12/19 之後
    else:
        return 1.465

# 4. 新增 Rf 欄位 (單位為 %，例如 1.09 代表 1.09%)
df['Rf'] = df['Date_tmp'].apply(get_rf)

# 5. 移除暫存日期欄位並儲存結果
df = df.drop(columns=['Date_tmp'])
output_name = 'Path_Result_with_Rf.csv'
df.to_csv(output_name, index=False, encoding='utf-8-sig')

# 6. 驗證結果
print(f"✅ 已成功處理 {len(df)} 筆資料，並新增 Rf 欄位。")
print("-" * 30)
# 顯示利率變動時間點的抽樣
print("利率對接抽樣檢查：")
print(df.iloc[[0, 60, 120, 180, 240]])
print("-" * 30)
print(f"請從左側下載檔案：{output_name}")

import pandas as pd

# 1. 讀取所有原始檔案
df_path = pd.read_excel('活頁簿1.xlsx')
df_expiry = pd.read_excel('期貨交易資料.xlsx')

# 2. 基本清洗與更名
df_path.columns = df_path.columns.str.strip()
df_expiry.columns = df_expiry.columns.str.strip()
df_path = df_path.rename(columns={'年月日': 'Date', '收盤價': 'S0', '收盤指數': 'S0'})
if 'S0' not in df_path.columns:
    df_path = df_path.rename(columns={df_path.columns[2]: 'S0'})

# 3. 處理月選擇權結算資料 (排除週合約 W)
df_expiry_monthly = df_expiry[~df_expiry['契約月份'].astype(str).str.contains('W')].copy()
df_expiry_monthly['最後結算日'] = pd.to_datetime(df_expiry_monthly['最後結算日'])
df_expiry_monthly = df_expiry_monthly.sort_values('最後結算日')

# 4. 轉換交易日期格式
df_path['Date_obj'] = pd.to_datetime(df_path['Date'])

# 5. 定義 2022 年 Rf 變動邏輯
def get_rf(date):
    if date < pd.Timestamp('2022-03-21'): return 0.840
    elif date < pd.Timestamp('2022-06-21'): return 1.090
    elif date < pd.Timestamp('2022-09-26'): return 1.215
    elif date < pd.Timestamp('2022-09-26'): return 1.215 # 補丁避免邏輯跳漏
    elif date < pd.Timestamp('2022-12-19'): return 1.340
    else: return 1.465

# 6. 定義合約對接邏輯 (距離結算日 > 1)
def get_contract_info(trade_date):
    mask = df_expiry_monthly['最後結算日'] > (trade_date + pd.Timedelta(days=1))
    valid = df_expiry_monthly[mask]

    if not valid.empty:
        target = valid.iloc[0]
        return pd.Series([
            target['契約月份'],
            target['最後結算日'],
            (target['最後結算日'] - trade_date).days
        ])
    else:
        # 年底補償邏輯：若缺 2023 資料，手動補上 2023/01 結算日 (2023-01-18)
        expiry_202301 = pd.Timestamp('2023-01-18')
        return pd.Series([
            '202301',
            expiry_202301,
            (expiry_202301 - trade_date).days
        ])

# 7. 執行對接運算
df_path[['Contract', 'ContractExpiryDate', 'Maturity']] = df_path['Date_obj'].apply(get_contract_info)
df_path['Rf'] = df_path['Date_obj'].apply(get_rf)

# 8. 格式化輸出欄位
df_path['File'] = df_path['Date_obj'].dt.strftime('OptionsDaily_%Y_%m_%d.csv')
df_path['Date'] = df_path['Date_obj'].dt.strftime('%Y/%-m/%-d')
df_path['ContractExpiryDate'] = df_path['ContractExpiryDate'].dt.strftime('%Y/%-m/%-d')

# 9. 挑選並排序所有要求的欄位
df_final = df_path[['Date', 'File', 'S0', 'Contract', 'ContractExpiryDate', 'Maturity', 'Rf']]

# 10. 輸出與預覽
output_name = 'Path_Final_Complete_All_Fields.csv'
df_final.to_csv(output_name, index=False, encoding='utf-8-sig')

print(f"✅ 成功生成 246 筆完整資料！")
print(f"包含欄位：Date, File, S0, Contract, ContractExpiryDate, Maturity, Rf")
print("-" * 30)
# 設定顯示所有欄位與行數
pd.set_option('display.max_columns', None)
print(df_final.to_string())
print("-" * 30)
print(f"請在左側下載檔案：{output_name}")

import pandas as pd
import numpy as np

# 1. 讀取檔案
df_path = pd.read_excel('活頁簿1.xlsx')
df_expiry = pd.read_excel('期貨交易資料.xlsx')

# 2. 基本清洗
df_path.columns = df_path.columns.str.strip()
df_expiry.columns = df_expiry.columns.str.strip()

# 統一欄位名稱 (年月日 -> Date, 價格 -> S0)
df_path = df_path.rename(columns={'年月日': 'Date', '收盤價': 'S0', '收盤指數': 'S0'})
if 'S0' not in df_path.columns:
    df_path = df_path.rename(columns={df_path.columns[2]: 'S0'})

# 3. 準備月選擇權結算日 (排除 W)
df_expiry_monthly = df_expiry[~df_expiry['契約月份'].astype(str).str.contains('W')].copy()
df_expiry_monthly['最後結算日'] = pd.to_datetime(df_expiry_monthly['最後結算日'])
df_expiry_monthly = df_expiry_monthly.sort_values('最後結算日')

# 4. 轉換交易日期
df_path['Date'] = pd.to_datetime(df_path['Date'])

# 5. 核心邏輯：對接合約與計算天數
def get_info(trade_date):
    # 條件：結算日 > 交易日 + 1
    mask = df_expiry_monthly['最後結算日'] > (trade_date + pd.Timedelta(days=1))
    valid = df_expiry_monthly[mask]

    if not valid.empty:
        target = valid.iloc[0]
        return pd.Series([target['契約月份'], (target['最後結算日'] - trade_date).days])
    else:
        # 針對年底資料若缺 2023 結算日的補償邏輯 (手動補上 2023/1/18)
        return pd.Series(['202301', (pd.Timestamp('2023-01-18') - trade_date).days])

# 6. 執行轉換 (確保 246 筆全部處理)
df_path[['Contract', 'Maturity']] = df_path['Date'].apply(get_info)

# 7. 格式化輸出
df_path['File'] = df_path['Date'].dt.strftime('OptionsDaily_%Y_%m_%d.csv')
df_path['Date_Str'] = df_path['Date'].dt.strftime('%Y/%-m/%-d')

# 8. 挑選最終 5 個欄位
df_final = df_path[['Date_Str', 'File', 'S0', 'Maturity', 'Contract']].rename(columns={'Date_Str': 'Date'})

# 9. 輸出與下載提示
output_name = 'Path_Result_246.csv'
df_final.to_csv(output_name, index=False, encoding='utf-8-sig')

# --- 強制印出所有資料 (或前 246 筆) ---
pd.set_option('display.max_rows', None)
print(f"✅ 處理完成！總共筆數: {len(df_final)}")
print("-" * 30)
print(df_final.to_string()) # 這會直接在畫面印出全部 246 筆
print("-" * 30)
print(f"請到左側資料夾下載: {output_name}")

import pandas as pd
import numpy as np

# 1. 讀取檔案
df_path = pd.read_excel('活頁簿1.xlsx')
df_expiry = pd.read_excel('期貨交易資料.xlsx')

# 2. 基本清洗
df_path.columns = df_path.columns.str.strip()
df_expiry.columns = df_expiry.columns.str.strip()

# 統一欄位名稱 (年月日 -> Date, 價格 -> S0)
df_path = df_path.rename(columns={'年月日': 'Date', '收盤價': 'S0', '收盤指數': 'S0'})
if 'S0' not in df_path.columns:
    df_path = df_path.rename(columns={df_path.columns[2]: 'S0'})

# 3. 準備月選擇權結算日 (排除 W)
df_expiry_monthly = df_expiry[~df_expiry['契約月份'].astype(str).str.contains('W')].copy()
df_expiry_monthly['最後結算日'] = pd.to_datetime(df_expiry_monthly['最後結算日'])
df_expiry_monthly = df_expiry_monthly.sort_values('最後結算日')

# 4. 轉換交易日期
df_path['Date'] = pd.to_datetime(df_path['Date'])

# 5. 核心邏輯：對接合約與計算天數
def get_info(trade_date):
    # 條件：結算日 > 交易日 + 1
    mask = df_expiry_monthly['最後結算日'] > (trade_date + pd.Timedelta(days=1))
    valid = df_expiry_monthly[mask]

    if not valid.empty:
        target = valid.iloc[0]
        return pd.Series([target['契約月份'], (target['最後結算日'] - trade_date).days])
    else:
        # 針對年底資料若缺 2023 結算日的補償邏輯 (手動補上 2023/1/18)
        return pd.Series(['202301', (pd.Timestamp('2023-01-18') - trade_date).days])

# 6. 執行轉換 (確保 246 筆全部處理)
df_path[['Contract', 'Maturity']] = df_path['Date'].apply(get_info)

# 7. 格式化輸出
df_path['File'] = df_path['Date'].dt.strftime('OptionsDaily_%Y_%m_%d.csv')
df_path['Date_Str'] = df_path['Date'].dt.strftime('%Y/%-m/%-d')

# 8. 挑選最終 5 個欄位
df_final = df_path[['Date_Str', 'File', 'S0', 'Maturity', 'Contract']].rename(columns={'Date_Str': 'Date'})

# 9. 輸出與下載提示
output_name = 'Path_Result_246.csv'
df_final.to_csv(output_name, index=False, encoding='utf-8-sig')

# --- 強制印出所有資料 (或前 246 筆) ---
pd.set_option('display.max_rows', None)
print(f"✅ 處理完成！總共筆數: {len(df_final)}")
print("-" * 30)
print(df_final.to_string()) # 這會直接在畫面印出全部 246 筆
print("-" * 30)
print(f"請到左側資料夾下載: {output_name}")

from google.colab import drive
drive.mount('/content/drive')